[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jax-diffusion-tutorial"
version = "0.0.1"
description = "Tutorial implementation of score-based diffusion models in JAX"
requires-python = ">=3.10"
